/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2a0c11e2-ae76-4055-8011-4956e6e2270d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_mys1Z4tWJ",
    "aws_user_pools_web_client_id": "6k6dal97ad16kvdmonoavtb4tk",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "fundsTable-dev",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "fundsApi",
            "endpoint": "https://wy7vh1ksrk.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
